openapi: 3.0.1
info:
  title: Eclipse Dataspace Connector Identity Hub
  version: 0.0.1
paths:
  /identity-hub:
    post:
      tags:
      - IdentityHub
      operationId: handleRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestObject'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseObject'
components:
  schemas:
    HubObject:
      type: object
    MessageResponseObject:
      type: object
      properties:
        messageId:
          type: string
        status:
          $ref: '#/components/schemas/MessageStatus'
        entries:
          type: array
          items:
            $ref: '#/components/schemas/HubObject'
    MessageStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        detail:
          type: string
    RequestStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        detail:
          type: string
    ResponseObject:
      type: object
      properties:
        requestId:
          type: string
        status:
          $ref: '#/components/schemas/RequestStatus'
        replies:
          type: array
          items:
            $ref: '#/components/schemas/MessageResponseObject'
    Descriptor:
      type: object
      properties:
        method:
          type: string
        nonce:
          type: string
        dataCid:
          type: string
        dataFormat:
          type: string
    MessageRequestObject:
      type: object
      properties:
        descriptor:
          $ref: '#/components/schemas/Descriptor'
        data:
          type: array
          items:
            type: string
            format: byte
    RequestObject:
      type: object
      properties:
        requestId:
          type: string
        target:
          type: string
        messages:
          type: array
          items:
            $ref: '#/components/schemas/MessageRequestObject'
